# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from openerp.osv import fields, osv


class stock_picking(osv.osv):
    _inherit = 'stock.picking'
    _columns = {
        'salesagent_id' : fields.many2one('res.partner', 'Agente'),
    }

    def _prepare_invoice(self, cr, uid, picking, partner, inv_type, journal_id, context=None):
        """ Inherit the original function of the 'stock' module in order to override some
            values if the picking has been generated by a sales order
        """
        invoice_vals = super(stock_picking, self)._prepare_invoice(cr, uid, picking, partner, inv_type, journal_id, context=context)
        if picking.salesagent_id:
            invoice_vals['salesagent_id'] = picking.salesagent_id.id
        return invoice_vals

    def _get_invoice_vals(self, cr, uid, key, inv_type, journal_id, move, context=None):
        res = super(stock_picking, self)._get_invoice_vals(cr, uid, key, inv_type, journal_id, move, context=context)
        if res:
            res.update({'salesagent_id':move.picking_id.salesagent_id.id})
        return res

    def onchange_partner_in(self, cr, uid, ids, partner_id=None, context=None):
        if not partner_id:
            return {}
        partner = self.pool.get('res.partner').read(cr, uid, partner_id, ['salesagent_for_customer_id'])
        salesagent_id = partner['salesagent_for_customer_id']
        res = super(stock_picking_out, self).onchange_partner_in(cr, uid, ids, partner_id, context)
        if 'value' not in res:
            if salesagent_id and 'value' not in res:
                return {'value': {'salesagent_id': salesagent_id,
                                  }}
            return {'value': {'salesagent_id': None,
                                  }}
        res['value']['salesagent_id'] = salesagent_id

        return res
